### ISSUE TITLE
SendFile failed with buffer

### ISSUE THREAD

**Issue by Calvin-Lin** [Yoctol/messaging-apis#334]
I tried
```
const buffer = Buffer.from(<csv string>);
client.sendFile(USER_ID, buffer);
```
Then got error
```
Error: Messenger API - 100 OAuthException (#100) Incorrect number of files uploaded. Must upload exactly one file.
    at handleError (/Users/dvlab/Desktop/CHT-bot/node_modules/messaging-api-messenger/lib/MessengerClient.js:63:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Error Message -
  Messenger API - 100 OAuthException (#100) Incorrect number of files uploaded. Must upload exactly one file.

Request -
  POST https://graph.facebook.com/v2.11/me/messages?access_token=<access_token>

Request Data -
  {
    "_overheadLength": 474,
    "_valueLength": 107,
    "_valuesToMeasure": [],
    "writable": false,
    "readable": true,
    "dataSize": 0,
    "maxDataSize": 2097152,
    "pauseStreams": true,
    "_released": true,
    "_streams": [],
    "_currentStream": null,
    "_boundary": "--------------------------416666756942652263281922",
    "_events": {},
    "_eventsCount": 0
  }

Response -
  400 Bad Request

Response Data -
  {
    "error": {
      "message": "(#100) Incorrect number of files uploaded. Must upload exactly one file.",
      "type": "OAuthException",
      "code": 100,
      "error_subcode": 2018005,
      "fbtrace_id": "EUKH++BUy3l"
    }
  }
```

**Comment by chentsulin** [comment]
relevant issue: https://github.com/Yoctol/messaging-apis/issues/223
