### ISSUE TITLE
[Viber] AxiosError: Viber API - undefined

### ISSUE THREAD

**Issue by randomhash** [Yoctol/messaging-apis#638]
No more info supplied. When initiating Viber client falling with such error, previously worked fine even with the old version(0.8.4), after upgrade error is the same

```
AxiosError: Viber API - undefined
    at ViberClient.<anonymous> (/home/b1/bot/10/lib/node_modules/messaging-api-viber/dist/ViberClient.js:84:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/b1/bot/10/lib/node_modules/messaging-api-viber/dist/ViberClient.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error Message -
  Viber API - undefined

Request -
  POST /set_webhook
```

**Comment by tw0517tw** [comment]
Hi @randomhash ,

Please provide more information about how to reproduce this error. For example, what methods did you call and what are the arguments.

**Comment by randomhash** [comment]
@tw0517tw hey, thanks for the reply

```
Request Data -
  {
    "url": "https://x.x.x.x/viber/webhook",
    "event_types": [
      "subscribed",
      "conversation_started"
    ]
  }

Response -
  200 OK

Response Data -
  {
    "status": 1,
    "chat_hostname": "SN-CHAT-06_"
  }
```


code

https://github.com/randomhash/chatbot-weather/blob/49399d8409929b2be9b35317c189c5a3dc1f2b1f/src/controllers/viber.ts#L17

Would be glad to have any help ;)
Can't find what status 1 means

**Comment by randomhash** [comment]
nvm, got my answer, sorry for the confusion
```
Set webhook callback
For each set_webhook request Viber will send a callback to the webhook URL to confirm it is available. The expected HTTP response to the callback is 200 OK – any other response will mean the webhook is not available. If the webhook is not available the set_webhook response sent to the user will be status 1: invalidUrl.

```
