### ISSUE TITLE
Cannot launch the script

### ISSUE THREAD

**Issue by bitbreakr** [Yoctol/messaging-apis#69]
I get this error when launching my js script after installation

(function (exports, require, module, __filename, __dirname) { import {
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by tw0517tw** [comment]
Hi @bitbreakr ,

It seems that you are not using babel for ES2015 modules, so you need to replace the `import` scripts with nodejs `require`.

for example, change from 
```js
import { MessengerClient } from 'messaging-api-messenger';
```
to
```js
const { MessengerClient } = require('messaging-api-messenger');
```

Sorry for not mentioning this in the documents.

**Comment by chentsulin** [comment]
Using `require` instead of `import` should resolve this issue, so I am going to close this. If it doesn't work, please reopen this again.
